[[redirects]]
  from = "/*"
  to = "https://localhost:8993/:splat"
  status = 200
  [redirects.headers]
    Test = "testing"
    X-Requested-With = "XMLHttpRequest"
    Authorization = "Basic YWRtaW46YWRtaW4="
    Host = "localhost:8993"